# Site settings
title: HY's Farm
email: dwhylee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cultivo-hy.github.io" # the base hostname & protocol for your site
github_username: cultivo-hy
permalink: pretty

# other links
github_username: cultivo-hy 
email: dwhylee@gmail.com

description_footer : "공부 및 개발에 대한 블로그입니다."

# comments
# two ways to comment, only choose one, and use your own short name
# disqus_shortname: astrod

google_analytics_id : UA-132682019-1


# Build settings
markdown: kramdown
rdiscount:
    extensions:
      - generate_toc

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 2 
